# -*- coding: utf-8 -*-
"""ProjectWeek6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y8edHq48-5QXfood1vewRWcY6pOPKDew
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.metrics import (
  classification_report,
  confusion_matrix,
  accuracy_score,
  precision_score,
  recall_score,
  f1_score,
  mean_squared_error,
  mean_absolute_error,
  r2_score,
  roc_curve,
  auc,
)
import warnings

warnings.filterwarnings('ignore')

print('='*70)
print('MLP Model Training and Testing - AIT 500 Project')
print('='*70)

# Load the cleaned dataset
print('\n[1] Loading Dataset...')
print('\n[1] Loading Dataset...')
url = "https://raw.githubusercontent.com/dipesh-giri01/social_media_analysis/refs/heads/main/train_cleaned.csv"
df = pd.read_csv(url)
print(f'Dataset shape: {df.shape}')
print(f'Rows: {df.shape[0]}, Columns: {df.shape[1]}')
print('\nFirst few rows:')
print(df.head())

# Display feature information
print('\n[2] Dataset Information:')
print(df.info())
print('\nDataset Statistics:')
print(df.describe())

# Check for missing values
print('\nMissing Values:')
print(df.isnull().sum())

# Define features and target
print('\n[3] Feature Selection and Engineering:')
print('MLPClassifier — 10 scaled features → high vs low engagement (median likes threshold).')
print('MLPRegressor — platform, post type, views, dates → predicts likes, shares, comments (multi-output).')

# Classification (same feature list as course snippet)
features_clf = [
  'platform_encoded',
  'post_type_encoded',
  'likes',
  'shares',
  'comments',
  'views',
  'year',
  'month',
  'day_of_week',
  'week_of_year',
]
X = df[features_clf]

# Regression targets (multi-output); inputs must not include those targets
features_reg = [
  'platform_encoded',
  'post_type_encoded',
  'views',
  'year',
  'month',
  'day_of_week',
  'week_of_year',
]

# Create target variable: High engagement (1) vs Low engagement (0)
# Using median of likes as threshold for binary classification
engagement_threshold = df['likes'].median()
y = (df['likes'] > engagement_threshold).astype(int)

print(f'\nTarget Variable: High Engagement Classification')
print(f'Threshold (Median Likes): {engagement_threshold}')
print(f'Class Distribution:')
print(f'  Low Engagement (0): {(y == 0).sum()} samples')
print(f'  High Engagement (1): {(y == 1).sum()} samples')

# Feature Scaling
print('\n[4] Feature Scaling:')
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print('Applied StandardScaler to all MLPClassifier inputs (10 features)')
print(f'Scaled feature range: Mean≈0, Std≈1')
print(f'\nScaling parameters:')
for i, col in enumerate(features_clf):
  print(f'  {col}: mean={scaler.mean_[i]:.2f}, std={scaler.scale_[i]:.2f}')

# Train-Test Split
print('\n[5] Train-Test Split:')
X_train, X_test, y_train, y_test = train_test_split(
  X_scaled, y, test_size=0.2, random_state=42
)

X_reg = df[features_reg]
scaler_reg = StandardScaler()
X_reg_scaled = scaler_reg.fit_transform(X_reg)
y_reg = df[['likes', 'shares', 'comments']].values
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
  X_reg_scaled, y_reg, test_size=0.2, random_state=42
)

print(f'Total samples: {len(X_scaled)}')
print(f'Training set: {len(X_train)} samples (80%)')
print(f'Testing set: {len(X_test)} samples (20%)')
print(f'\nTraining set class distribution:')
print(f'  Low Engagement: {(y_train == 0).sum()} samples')
print(f'  High Engagement: {(y_train == 1).sum()} samples')
print(f'\nTesting set class distribution:')
print(f'  Low Engagement: {(y_test == 0).sum()} samples')
print(f'  High Engagement: {(y_test == 1).sum()} samples')

# MLP Model Configuration
print('\n[6] MLP Model Configuration:')
print('Model Architecture:')
print('  Hidden layers: (100, 50)')
print('    - Layer 1: 100 neurons')
print('    - Layer 2: 50 neurons')
print('  Activation function: ReLU (Rectified Linear Unit)')
print('  Solver/Optimizer: Adam')
print('  Learning rate: Adaptive')
print('  Max iterations: 300')
print('  Random state: 42')

mlp_model = MLPClassifier(
  hidden_layer_sizes=(100, 50),
  activation='relu',
  solver='adam',
  learning_rate='adaptive',
  max_iter=300,
  random_state=42,
  early_stopping=True,
  validation_fraction=0.1,
  n_iter_no_change=20,
  verbose=0,
)

# Train the model
print('\n[7] Training the MLP Model:')
print('Training in progress...')
mlp_model.fit(X_train, y_train)
print('✓ MLPClassifier training completed!')
print(f'Converged at iteration: {mlp_model.n_iter_}')
print(f'Final training loss:    {mlp_model.loss_:.4f}')

# MLPClassifier — training loss + validation score (same structure as course snippet)
if hasattr(mlp_model, 'loss_curve_') and mlp_model.loss_curve_ is not None:
  loss_curve = np.asarray(mlp_model.loss_curve_, dtype=float)
  n_curve = len(loss_curve)
  epochs = np.arange(n_curve)
  conv_idx = n_curve - 1

  fig_lc, ax1_lc = plt.subplots(figsize=(10, 6))
  ax1_lc.plot(epochs, loss_curve, color='steelblue', linewidth=2, label='Training Loss')
  ax1_lc.set_xlabel('Epoch / Iteration', fontsize=12)
  ax1_lc.set_ylabel('Training Loss', color='steelblue', fontsize=12)
  ax1_lc.tick_params(axis='y', labelcolor='steelblue')

  ax2_lc = None
  val_scores = getattr(mlp_model, 'validation_scores_', None)
  if val_scores is not None and len(val_scores) > 0:
    val_scores = np.asarray(val_scores, dtype=float)
    val_epochs = np.arange(len(val_scores))
    ax2_lc = ax1_lc.twinx()
    ax2_lc.plot(
      val_epochs,
      val_scores,
      color='coral',
      linewidth=2,
      linestyle='--',
      label='Validation Score',
    )
    ax2_lc.set_ylabel('Validation Score', color='coral', fontsize=12)
    ax2_lc.tick_params(axis='y', labelcolor='coral')

  ax1_lc.axvline(
    x=conv_idx,
    color='green',
    linestyle=':',
    linewidth=1.8,
    label=f'Early Stop (iter {mlp_model.n_iter_})',
  )
  if conv_idx >= 0:
    ann_x = min(conv_idx + 1.5, n_curve + 0.5)
    ax1_lc.annotate(
      f'Stopped at\niteration {mlp_model.n_iter_}',
      xy=(conv_idx, loss_curve[conv_idx]),
      xytext=(ann_x, float(loss_curve[0]) * 0.6),
      arrowprops=dict(arrowstyle='->', color='green'),
      fontsize=10,
      color='green',
    )

  lines1, labels1 = ax1_lc.get_legend_handles_labels()
  if ax2_lc is not None:
    lines2, labels2 = ax2_lc.get_legend_handles_labels()
    ax1_lc.legend(lines1 + lines2, labels1 + labels2, loc='center right', fontsize=10)
  else:
    ax1_lc.legend(lines1, labels1, loc='center right', fontsize=10)

  ax1_lc.set_title(
    f'MLP Classifier — Training Loss Curve (Converged at Iteration {mlp_model.n_iter_})',
    fontweight='bold',
    fontsize=13,
  )
  ax1_lc.grid(alpha=0.3)
  plt.tight_layout()
  plt.savefig('loss_curve.png', dpi=300, bbox_inches='tight')
  plt.close(fig_lc)
  print('✓ Saved loss_curve.png (MLPClassifier: 10 features, median-likes label, early stopping)')

print('\n[7b] Training MLP Regressor (predict likes, shares, comments):')
mlp_reg = MLPRegressor(
  hidden_layer_sizes=(100, 50),
  activation='relu',
  solver='adam',
  max_iter=300,
  random_state=42,
)
mlp_reg.fit(X_train_reg, y_train_reg)
print('✓ MLPRegressor training completed!')
print(f'Converged at iteration: {mlp_reg.n_iter_}')
print(f'Final training loss:    {mlp_reg.loss_:.4f}')

# MLPRegressor — training loss curve (multi-output; no validation curve unless early_stopping is enabled)
if hasattr(mlp_reg, 'loss_curve_') and mlp_reg.loss_curve_ is not None:
  reg_lc = np.asarray(mlp_reg.loss_curve_, dtype=float)
  reg_epochs = np.arange(len(reg_lc))
  fig_rl, ax_rl = plt.subplots(figsize=(10, 6))
  ax_rl.plot(reg_epochs, reg_lc, color='darkviolet', linewidth=2, label='Training Loss')
  ax_rl.set_xlabel('Epoch / Iteration', fontsize=12)
  ax_rl.set_ylabel('Training Loss', fontsize=12)
  ax_rl.set_title(
    f'MLP Regressor — Training Loss Curve (n_iter={mlp_reg.n_iter_})',
    fontweight='bold',
    fontsize=13,
  )
  ax_rl.legend(loc='upper right', fontsize=10)
  ax_rl.grid(alpha=0.3)
  plt.tight_layout()
  plt.savefig('loss_curve_regressor.png', dpi=300, bbox_inches='tight')
  plt.close(fig_rl)
  print('✓ Saved loss_curve_regressor.png (MLPRegressor: 3 targets, Adam + ReLU)')

# Combined figure: classifier vs regressor training loss (one image for reports)
if (
  hasattr(mlp_model, 'loss_curve_') and mlp_model.loss_curve_ is not None
  and hasattr(mlp_reg, 'loss_curve_') and mlp_reg.loss_curve_ is not None
):
  lc_c = np.asarray(mlp_model.loss_curve_, dtype=float)
  lc_r = np.asarray(mlp_reg.loss_curve_, dtype=float)
  fig_both, (ax_c, ax_r) = plt.subplots(1, 2, figsize=(14, 5.2), constrained_layout=True)
  fig_both.suptitle('MLP training loss — classifier vs regressor', fontsize=14, fontweight='bold')

  ep_c = np.arange(len(lc_c))
  ax_c.plot(ep_c, lc_c, color='steelblue', linewidth=2, label='Training loss')
  ax_c.set_xlabel('Epoch / iteration', fontsize=11)
  ax_c.set_ylabel('Training loss', color='steelblue', fontsize=11)
  ax_c.tick_params(axis='y', labelcolor='steelblue')
  val_b = getattr(mlp_model, 'validation_scores_', None)
  if val_b is not None and len(val_b) > 0:
    val_b = np.asarray(val_b, dtype=float)
    ax_cv = ax_c.twinx()
    ax_cv.plot(np.arange(len(val_b)), val_b, color='coral', linestyle='--', linewidth=2, label='Validation score')
    ax_cv.set_ylabel('Validation score', color='coral', fontsize=11)
    ax_cv.tick_params(axis='y', labelcolor='coral')
    h1, l1 = ax_c.get_legend_handles_labels()
    h2, l2 = ax_cv.get_legend_handles_labels()
    ax_c.legend(h1 + h2, l1 + l2, loc='upper right', fontsize=9)
  else:
    ax_c.legend(loc='upper right', fontsize=9)
  ax_c.set_title(f'MLPClassifier (n_iter={mlp_model.n_iter_})', fontweight='bold', fontsize=12)
  ax_c.grid(alpha=0.3)

  ep_r = np.arange(len(lc_r))
  ax_r.plot(ep_r, lc_r, color='darkviolet', linewidth=2, label='Training loss')
  ax_r.set_xlabel('Epoch / iteration', fontsize=11)
  ax_r.set_ylabel('Training loss', fontsize=11)
  ax_r.set_title(f'MLPRegressor (n_iter={mlp_reg.n_iter_})', fontweight='bold', fontsize=12)
  ax_r.legend(loc='upper right', fontsize=9)
  ax_r.grid(alpha=0.3)

  plt.savefig('11_mlp_training_loss_classifier_and_regressor.png', dpi=300, bbox_inches='tight', facecolor='white')
  plt.close(fig_both)
  print('✓ Saved 11_mlp_training_loss_classifier_and_regressor.png')

# Make predictions
print('\n[8] Model Predictions:')
y_train_pred = mlp_model.predict(X_train)
y_test_pred = mlp_model.predict(X_test)

# Evaluate on training set
print('\n' + '='*70)
print('TRAINING SET PERFORMANCE')
print('='*70)
train_accuracy = accuracy_score(y_train, y_train_pred)
train_precision = precision_score(y_train, y_train_pred)
train_recall = recall_score(y_train, y_train_pred)
train_f1 = f1_score(y_train, y_train_pred)

print(f'Accuracy:  {train_accuracy:.4f} ({train_accuracy*100:.2f}%)')
print(f'Precision: {train_precision:.4f}')
print(f'Recall:    {train_recall:.4f}')
print(f'F1-Score:  {train_f1:.4f}')

print('\nClassification Report (Training Set):')
print(classification_report(y_train, y_train_pred, target_names=['Low Engagement', 'High Engagement']))

print('Confusion Matrix (Training Set):')
cm_train = confusion_matrix(y_train, y_train_pred)
print(cm_train)
print(f'  True Negatives: {cm_train[0, 0]}')
print(f'  False Positives: {cm_train[0, 1]}')
print(f'  False Negatives: {cm_train[1, 0]}')
print(f'  True Positives: {cm_train[1, 1]}')

# Evaluate on testing set
print('\n' + '='*70)
print('TESTING SET PERFORMANCE')
print('='*70)
test_accuracy = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred)
test_recall = recall_score(y_test, y_test_pred)
test_f1 = f1_score(y_test, y_test_pred)

print(f'Accuracy:  {test_accuracy:.4f} ({test_accuracy*100:.2f}%)')
print(f'Precision: {test_precision:.4f}')
print(f'Recall:    {test_recall:.4f}')
print(f'F1-Score:  {test_f1:.4f}')

print('\nClassification Report (Testing Set):')
print(classification_report(y_test, y_test_pred, target_names=['Low Engagement', 'High Engagement']))

print('Confusion Matrix (Testing Set):')
cm_test = confusion_matrix(y_test, y_test_pred)
print(cm_test)
print(f'  True Negatives: {cm_test[0, 0]}')
print(f'  False Positives: {cm_test[0, 1]}')
print(f'  False Negatives: {cm_test[1, 0]}')
print(f'  True Positives: {cm_test[1, 1]}')

# Regression evaluation (test set, multi-output: likes, shares, comments)
y_pred_reg = mlp_reg.predict(X_test_reg)
reg_mse = mean_squared_error(y_test_reg, y_pred_reg, multioutput='uniform_average')
reg_mae = mean_absolute_error(y_test_reg, y_pred_reg, multioutput='uniform_average')
reg_r2 = r2_score(y_test_reg, y_pred_reg, multioutput='uniform_average')
reg_targets = ('likes', 'shares', 'comments')
r2_per = r2_score(y_test_reg, y_pred_reg, multioutput='raw_values')
mae_per = mean_absolute_error(y_test_reg, y_pred_reg, multioutput='raw_values')
mse_per = np.array(
  [mean_squared_error(y_test_reg[:, i], y_pred_reg[:, i]) for i in range(y_test_reg.shape[1])],
  dtype=float,
)
print('\n' + '='*70)
print('REGRESSION (TEST SET) — predict likes, shares, comments')
print('='*70)
print(f'Average MSE (uniform over targets): {reg_mse:.2f}')
print(f'Average MAE (uniform over targets): {reg_mae:.2f}')
print(f'Average R² (uniform over targets): {reg_r2:.4f}')
for i, name in enumerate(reg_targets):
  print(f'  {name}: MAE={mae_per[i]:.2f}, MSE={mse_per[i]:.2f}, R²={r2_per[i]:.4f}')

# Graphs: classifier (ROC) and regressor (predicted vs actual) on test set
y_score_test = mlp_model.predict_proba(X_test)[:, 1]
fpr, tpr, _ = roc_curve(y_test, y_score_test)
roc_auc = auc(fpr, tpr)

fig_roc, ax_roc = plt.subplots(figsize=(7, 6))
ax_roc.plot(fpr, tpr, color='steelblue', linewidth=2, label=f'ROC (AUC = {roc_auc:.4f})')
ax_roc.plot([0, 1], [0, 1], color='gray', linestyle='--', linewidth=1, label='Chance')
ax_roc.set_xlabel('False positive rate', fontsize=12)
ax_roc.set_ylabel('True positive rate', fontsize=12)
ax_roc.set_title('MLPClassifier — ROC curve (test set)', fontweight='bold', fontsize=13)
ax_roc.legend(loc='lower right', fontsize=11)
ax_roc.grid(alpha=0.3)
ax_roc.set_aspect('equal', adjustable='box')
plt.tight_layout()
plt.savefig('12_classifier_roc_curve_test.png', dpi=300, bbox_inches='tight', facecolor='white')
plt.close(fig_roc)
print('✓ Saved 12_classifier_roc_curve_test.png')

fig_pv = plt.figure(figsize=(14, 7.2), constrained_layout=True)
gs = fig_pv.add_gridspec(2, 3, height_ratios=[2.1, 1], hspace=0.22, wspace=0.28)
fig_pv.suptitle(
  'MLPRegressor — test set: predicted vs actual + MAE / MSE / R²',
  fontsize=13,
  fontweight='bold',
)

axes_pv = [fig_pv.add_subplot(gs[0, i]) for i in range(3)]
for i, name in enumerate(reg_targets):
  yt = y_test_reg[:, i]
  yp = y_pred_reg[:, i]
  lo = min(yt.min(), yp.min())
  hi = max(yt.max(), yp.max())
  axes_pv[i].scatter(yt, yp, alpha=0.5, edgecolors='none', s=28, c='darkviolet')
  axes_pv[i].plot([lo, hi], [lo, hi], 'k--', linewidth=1, label='Perfect fit')
  axes_pv[i].set_xlabel(f'Actual {name}', fontsize=11)
  axes_pv[i].set_ylabel(f'Predicted {name}', fontsize=11)
  axes_pv[i].set_title(str(name).capitalize(), fontsize=12, fontweight='bold')
  axes_pv[i].legend(loc='lower right', fontsize=9)
  axes_pv[i].grid(alpha=0.3)
  box_txt = (
    f'MAE = {mae_per[i]:.2f}\n'
    f'MSE = {mse_per[i]:.2f}\n'
    f'R²  = {r2_per[i]:.4f}'
  )
  axes_pv[i].text(
    0.03,
    0.97,
    box_txt,
    transform=axes_pv[i].transAxes,
    va='top',
    ha='left',
    fontsize=10,
    family='monospace',
    bbox=dict(boxstyle='round,pad=0.35', facecolor='#f5f0e6', edgecolor='#8b7355', alpha=0.95),
  )

ax_tbl = fig_pv.add_subplot(gs[1, :])
ax_tbl.axis('off')
table_rows = [
  [name.capitalize(), f'{mae_per[i]:.2f}', f'{mse_per[i]:.2f}', f'{r2_per[i]:.4f}']
  for i, name in enumerate(reg_targets)
]
table_rows.append(
  ['Average (uniform)', f'{reg_mae:.2f}', f'{reg_mse:.2f}', f'{reg_r2:.4f}'],
)
tbl = ax_tbl.table(
  cellText=table_rows,
  colLabels=['Target (test)', 'MAE', 'Mean squared error (MSE)', 'R²'],
  loc='center',
  cellLoc='center',
)
tbl.auto_set_font_size(False)
tbl.set_fontsize(11)
tbl.scale(1.05, 2.0)
for (row, col), cell in tbl.get_celld().items():
  if row == 0:
    cell.set_facecolor('#4a6785')
    cell.set_text_props(color='white', fontweight='bold')
  elif row == len(table_rows):
    cell.set_facecolor('#e8ecf0')
  else:
    cell.set_facecolor('#ffffff' if row % 2 else '#f7f9fc')

plt.savefig('13_regression_predicted_vs_actual_test.png', dpi=300, bbox_inches='tight', facecolor='white')
plt.close(fig_pv)
print('✓ Saved 13_regression_predicted_vs_actual_test.png (with MAE, MSE, R² table)')

# Classification vs regression — task comparison
comparison_df = pd.DataFrame(
  {
    'Aspect': [
      'Problem type',
      'What we predict',
      'Target (label)',
      'Key inputs (examples)',
      'Output',
    ],
    'Regression': [
      'Predict numbers (multi-output)',
      'Likes, shares, and comment counts for the post',
      'Three continuous targets: likes, shares, comments',
      'Platform, post type, views, year/month/day/week (not likes/shares/comments)',
      'Three continuous values per post',
    ],
    'Classification': [
      'Predict a category',
      'High vs low engagement (viral or not)',
      f'1 if likes > median ({engagement_threshold:.0f}), else 0',
      'platform, post type, likes, shares, comments, views, year, month, day, week',
      'Yes / No (high vs low engagement)',
    ],
  }
)
print('\n' + '='*70)
print('CLASSIFICATION VS REGRESSION — COMPARISON')
print('='*70)
print(comparison_df.to_string(index=False))

# Model comparison summary
print('\n' + '='*70)
print('MODEL PERFORMANCE SUMMARY')
print('='*70)
print(f'{"Metric":<20} {"Training":<15} {"Testing":<15} {"Difference":<15}')
print('-'*70)
print(f'{"Accuracy":<20} {train_accuracy:.4f}{"":<10} {test_accuracy:.4f}{"":<10} {abs(train_accuracy - test_accuracy):.4f}')
print(f'{"Precision":<20} {train_precision:.4f}{"":<10} {test_precision:.4f}{"":<10} {abs(train_precision - test_precision):.4f}')
print(f'{"Recall":<20} {train_recall:.4f}{"":<10} {test_recall:.4f}{"":<10} {abs(train_recall - test_recall):.4f}')
print(f'{"F1-Score":<20} {train_f1:.4f}{"":<10} {test_f1:.4f}{"":<10} {abs(train_f1 - test_f1):.4f}')

# Visualization - Individual images for each statistic
print('\n[9] Generating Individual Visualizations...')

# 1. Confusion Matrix - Training
fig1, ax1 = plt.subplots(figsize=(8, 6))
sns.heatmap(
  cm_train,
  annot=True,
  fmt='d',
  cmap='Blues',
  ax=ax1,
  cbar=True,
  xticklabels=['Low Engagement', 'High Engagement'],
  yticklabels=['Low Engagement', 'High Engagement'],
  cbar_kws={'label': 'Count'},
)
ax1.set_title('Confusion Matrix - Training Set', fontweight='bold', fontsize=14)
ax1.set_ylabel('True Label', fontsize=12)
ax1.set_xlabel('Predicted Label', fontsize=12)
plt.tight_layout()
plt.savefig('01_confusion_matrix_training.png', dpi=300, bbox_inches='tight')
print('✓ Image 1 saved: 01_confusion_matrix_training.png')
plt.close()

# 2. Confusion Matrix - Testing
fig2, ax2 = plt.subplots(figsize=(8, 6))
sns.heatmap(
  cm_test,
  annot=True,
  fmt='d',
  cmap='Greens',
  ax=ax2,
  cbar=True,
  xticklabels=['Low Engagement', 'High Engagement'],
  yticklabels=['Low Engagement', 'High Engagement'],
  cbar_kws={'label': 'Count'},
)
ax2.set_title('Confusion Matrix - Testing Set', fontweight='bold', fontsize=14)
ax2.set_ylabel('True Label', fontsize=12)
ax2.set_xlabel('Predicted Label', fontsize=12)
plt.tight_layout()
plt.savefig('02_confusion_matrix_testing.png', dpi=300, bbox_inches='tight')
print('✓ Image 2 saved: 02_confusion_matrix_testing.png')
plt.close()

# 3. Performance Metrics Comparison
fig3, ax3 = plt.subplots(figsize=(10, 6))
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
train_scores = [train_accuracy, train_precision, train_recall, train_f1]
test_scores = [test_accuracy, test_precision, test_recall, test_f1]

x = np.arange(len(metrics))
width = 0.35
bars1 = ax3.bar(x - width/2, train_scores, width, label='Training', alpha=0.8, color='steelblue')
bars2 = ax3.bar(x + width/2, test_scores, width, label='Testing', alpha=0.8, color='darkorange')

ax3.set_ylabel('Score', fontsize=12)
ax3.set_title('Model Performance Metrics Comparison', fontweight='bold', fontsize=14)
ax3.set_xticks(x)
ax3.set_xticklabels(metrics)
ax3.legend(fontsize=11)
ax3.set_ylim([0, 1.1])
ax3.grid(axis='y', alpha=0.3)

# Add value labels on bars
for bars in [bars1, bars2]:
  for bar in bars:
    height = bar.get_height()
    ax3.text(bar.get_x() + bar.get_width()/2., height,
            f'{height:.3f}', ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.savefig('03_performance_metrics_comparison.png', dpi=300, bbox_inches='tight')
print('✓ Image 3 saved: 03_performance_metrics_comparison.png')
plt.close()

# 4. Feature Importance
fig4, ax4 = plt.subplots(figsize=(10, 7))
feature_importance = np.abs(mlp_model.coefs_[0]).mean(axis=1)
feature_names_short = [
  'Platform',
  'Post Type',
  'Likes',
  'Shares',
  'Comments',
  'Views',
  'Year',
  'Month',
  'Day of Week',
  'Week of Year',
]
sorted_idx = np.argsort(feature_importance)
colors = plt.cm.viridis(np.linspace(0, 1, len(sorted_idx)))
ax4.barh(
  [feature_names_short[i] for i in sorted_idx],
  feature_importance[sorted_idx],
  alpha=0.8,
  color=colors,
)
ax4.set_xlabel('Average Absolute Weight', fontsize=12)
ax4.set_title('Feature Importance (Layer 1 Weights)', fontweight='bold', fontsize=14)
ax4.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig('04_feature_importance.png', dpi=300, bbox_inches='tight')
print('✓ Image 4 saved: 04_feature_importance.png')
plt.close()

# 5. Training vs Testing Accuracy
fig5, ax5 = plt.subplots(figsize=(8, 6))
datasets = ['Training', 'Testing']
accuracies = [train_accuracy, test_accuracy]
colors_acc = ['#2ecc71', '#e74c3c']
bars = ax5.bar(datasets, accuracies, color=colors_acc, alpha=0.8, width=0.5)
ax5.set_ylabel('Accuracy', fontsize=12)
ax5.set_title('Overall Model Accuracy Comparison', fontweight='bold', fontsize=14)
ax5.set_ylim([0, 1.1])
ax5.grid(axis='y', alpha=0.3)
for i, (bar, acc) in enumerate(zip(bars, accuracies)):
  ax5.text(bar.get_x() + bar.get_width()/2., acc + 0.02,
          f'{acc:.4f}\n({acc*100:.2f}%)', ha='center', va='bottom', fontsize=11, fontweight='bold')
plt.tight_layout()
plt.savefig('05_accuracy_comparison.png', dpi=300, bbox_inches='tight')
print('✓ Image 5 saved: 05_accuracy_comparison.png')
plt.close()

# 6. Precision Comparison
fig6, ax6 = plt.subplots(figsize=(8, 6))
precisions = [train_precision, test_precision]
bars = ax6.bar(datasets, precisions, color=colors_acc, alpha=0.8, width=0.5)
ax6.set_ylabel('Precision', fontsize=12)
ax6.set_title('Model Precision Comparison', fontweight='bold', fontsize=14)
ax6.set_ylim([0, 1.1])
ax6.grid(axis='y', alpha=0.3)
for i, (bar, prec) in enumerate(zip(bars, precisions)):
  ax6.text(bar.get_x() + bar.get_width()/2., prec + 0.02,
          f'{prec:.4f}', ha='center', va='bottom', fontsize=11, fontweight='bold')
plt.tight_layout()
plt.savefig('06_precision_comparison.png', dpi=300, bbox_inches='tight')
print('✓ Image 6 saved: 06_precision_comparison.png')
plt.close()

# 7. Recall Comparison
fig7, ax7 = plt.subplots(figsize=(8, 6))
recalls = [train_recall, test_recall]
bars = ax7.bar(datasets, recalls, color=colors_acc, alpha=0.8, width=0.5)
ax7.set_ylabel('Recall', fontsize=12)
ax7.set_title('Model Recall Comparison', fontweight='bold', fontsize=14)
ax7.set_ylim([0, 1.1])
ax7.grid(axis='y', alpha=0.3)
for i, (bar, rec) in enumerate(zip(bars, recalls)):
  ax7.text(bar.get_x() + bar.get_width()/2., rec + 0.02,
          f'{rec:.4f}', ha='center', va='bottom', fontsize=11, fontweight='bold')
plt.tight_layout()
plt.savefig('07_recall_comparison.png', dpi=300, bbox_inches='tight')
print('✓ Image 7 saved: 07_recall_comparison.png')
plt.close()

# 8. F1-Score Comparison
fig8, ax8 = plt.subplots(figsize=(8, 6))
f1_scores = [train_f1, test_f1]
bars = ax8.bar(datasets, f1_scores, color=colors_acc, alpha=0.8, width=0.5)
ax8.set_ylabel('F1-Score', fontsize=12)
ax8.set_title('Model F1-Score Comparison', fontweight='bold', fontsize=14)
ax8.set_ylim([0, 1.1])
ax8.grid(axis='y', alpha=0.3)
for i, (bar, f1) in enumerate(zip(bars, f1_scores)):
  ax8.text(bar.get_x() + bar.get_width()/2., f1 + 0.02,
          f'{f1:.4f}', ha='center', va='bottom', fontsize=11, fontweight='bold')
plt.tight_layout()
plt.savefig('08_f1_score_comparison.png', dpi=300, bbox_inches='tight')
print('✓ Image 8 saved: 08_f1_score_comparison.png')
plt.close()

# 9. All metrics in individual bar chart
fig9, ax9 = plt.subplots(figsize=(12, 6))
metrics_all = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
train_values = [train_accuracy, train_precision, train_recall, train_f1]
test_values = [test_accuracy, test_precision, test_recall, test_f1]

x = np.arange(len(metrics_all))
width = 0.35
bars1 = ax9.bar(x - width/2, train_values, width, label='Training', alpha=0.85, color='steelblue')
bars2 = ax9.bar(x + width/2, test_values, width, label='Testing', alpha=0.85, color='coral')

ax9.set_ylabel('Score', fontsize=12)
ax9.set_xlabel('Metrics', fontsize=12)
ax9.set_title('Complete Performance Metrics Comparison', fontweight='bold', fontsize=14)
ax9.set_xticks(x)
ax9.set_xticklabels(metrics_all)
ax9.legend(fontsize=11)
ax9.set_ylim([0, 1.15])
ax9.grid(axis='y', alpha=0.3)

for bars in [bars1, bars2]:
  for bar in bars:
    height = bar.get_height()
    ax9.text(bar.get_x() + bar.get_width()/2., height + 0.01,
            f'{height:.3f}', ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.savefig('09_all_metrics_combined.png', dpi=300, bbox_inches='tight')
print('✓ Image 9 saved: 09_all_metrics_combined.png')
plt.close()

# 10. MLP regression vs classification — table figure
def _style_table(tbl, header_color='#2c5282'):
  tbl.auto_set_font_size(False)
  tbl.set_fontsize(10)
  tbl.scale(1.05, 2.15)
  for (row, col), cell in tbl.get_celld().items():
    if row == 0:
      cell.set_facecolor(header_color)
      cell.set_text_props(color='white', fontweight='bold')
      cell.set_height(0.08)
    else:
      cell.set_facecolor('#edf2f7' if row % 2 == 1 else '#ffffff')

metrics_compare = pd.DataFrame(
  {
    'Test metric': [
      'Accuracy',
      'Precision',
      'Recall',
      'F1-Score',
      'R²',
      'MAE (likes)',
      'MSE (likes²)',
    ],
    'MLP classification': [
      f'{test_accuracy:.4f}',
      f'{test_precision:.4f}',
      f'{test_recall:.4f}',
      f'{test_f1:.4f}',
      '—',
      '—',
      '—',
    ],
    'MLP regression': [
      '—',
      '—',
      '—',
      '—',
      f'{reg_r2:.4f} (avg over 3 targets)',
      f'{reg_mae:.2f} (avg)',
      f'{reg_mse:.2f} (avg)',
    ],
  }
)

fig_cmp, (ax_a, ax_b) = plt.subplots(
  2,
  1,
  figsize=(14, 9.5),
  gridspec_kw={'height_ratios': [1.2, 1]},
)
fig_cmp.suptitle(
  'MLP Regression vs Classification',
  fontsize=16,
  fontweight='bold',
  y=0.98,
)
ax_a.axis('off')
ax_a.set_title('Task and setup comparison', loc='left', fontsize=12, fontweight='bold', pad=12)
t1 = ax_a.table(
  cellText=comparison_df.values,
  colLabels=list(comparison_df.columns),
  loc='center',
  cellLoc='left',
)
_style_table(t1)

ax_b.axis('off')
ax_b.set_title(
  'Test-set performance (classification: class metrics; regression: avg over likes/shares/comments)',
  loc='left',
  fontsize=11,
  fontweight='bold',
  pad=12,
)
t2 = ax_b.table(
  cellText=metrics_compare.values,
  colLabels=list(metrics_compare.columns),
  loc='center',
  cellLoc='center',
)
_style_table(t2)

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.savefig(
  '10_mlp_regression_vs_classification_table.png',
  dpi=300,
  bbox_inches='tight',
  facecolor='white',
)
plt.close(fig_cmp)
print('✓ Image 10 saved: 10_mlp_regression_vs_classification_table.png')

print('\n✓ All individual visualization images generated successfully!')

# Additional analysis
print('\n[10] Additional Analysis:')
print('\nPrediction Statistics (Testing Set):')
print(f'Predictions - Low Engagement: {(y_test_pred == 0).sum()}')
print(f'Predictions - High Engagement: {(y_test_pred == 1).sum()}')
print(f'Actual - Low Engagement: {(y_test == 0).sum()}')
print(f'Actual - High Engagement: {(y_test == 1).sum()}')

# Model summary
print('\n' + '='*70)
print('MODEL SUMMARY')
print('='*70)
print('Classification model: MLPClassifier (10 inputs: platform, post type, likes, shares, comments, views, dates)')
print('Regression model: MLPRegressor (targets: likes, shares, comments; other columns as inputs)')
print(f'Number of features (classification): {X_train.shape[1]}')
print(f'Number of features (regression inputs): {X_train_reg.shape[1]}')
print(f'Number of regression targets: {y_train_reg.shape[1]}')
print(f'Number of Training Samples: {X_train.shape[0]}')
print(f'Number of Testing Samples: {X_test.shape[0]}')
print(f'Hidden Layer Sizes: (100, 50)')
print(f'Activation Function: ReLU')
print(f'Optimizer: Adam')
print(f'Number of Iterations: {mlp_model.n_iter_}')
print(f'Final Loss: {mlp_model.loss_:.4f}')
print(f'\nBest Performing Metric (Testing):')
best_metric = max(
  [
    ('Accuracy', test_accuracy),
    ('Precision', test_precision),
    ('Recall', test_recall),
    ('F1-Score', test_f1),
  ],
  key=lambda x: x[1],
)
print(f'  {best_metric[0]}: {best_metric[1]:.4f}')

print('\n' + '='*70)
print('Training and Testing Complete!')
print('='*70)