# -*- coding: utf-8 -*-
"""Week7 Evaualtion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15M-YfdtJ50_SFDndShnJXCNg1uypAunN
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.metrics import (
  classification_report,
  confusion_matrix,
  accuracy_score,
  precision_score,
  recall_score,
  f1_score,
  mean_squared_error,
  mean_absolute_error,
  r2_score,
  roc_curve,
  auc,
)
import warnings

warnings.filterwarnings("ignore")

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1 — LOAD & INSPECT DATASET
# ─────────────────────────────────────────────────────────────────────────────
print("=" * 70)
print("MLP Model — Evaluation & Refinement  |  AIT 500 Project")
print("Dipesh Giri, Simon Sharma, Kushal Gautam")
print("=" * 70)

print("\n[1] Loading Dataset...")
url = "https://raw.githubusercontent.com/dipesh-giri01/social_media_analysis/refs/heads/main/train_cleaned.csv"
# df = pd.read_csv("train_cleaned.csv") for local
# for collab
df = pd.read_csv(url)
print(f"Dataset shape: {df.shape}  ({df.shape[0]} rows, {df.shape[1]} columns)")
print(f"\nFirst 5 rows:\n{df.head()}")

print("\n[2] Dataset Information:")
print(df.info())
print("\nDescriptive Statistics:")
print(df.describe())

print("\nMissing Values:")
print(df.isnull().sum())

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2 — FEATURE SELECTION & TARGET ENGINEERING
# ─────────────────────────────────────────────────────────────────────────────
print("\n[3] Feature Selection and Engineering:")
print("  MLPClassifier — 10 features → binary high/low engagement (median likes threshold)")
print("  MLPRegressor  — 7 features  → predict likes, shares, comments (multi-output)")

features_clf = [
  "platform_encoded",
  "post_type_encoded",
  "likes",
  "shares",
  "comments",
  "views",
  "year",
  "month",
  "day_of_week",
  "week_of_year",
]

features_reg = [
  "platform_encoded",
  "post_type_encoded",
  "views",
  "year",
  "month",
  "day_of_week",
  "week_of_year",
]

engagement_threshold = df["likes"].median()
y = (df["likes"] > engagement_threshold).astype(int)

print(f"\nEngagement threshold (median likes): {engagement_threshold}")
print(f"  Low Engagement  (0): {(y == 0).sum()} samples")
print(f"  High Engagement (1): {(y == 1).sum()} samples")

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3 — FEATURE SCALING & TRAIN/TEST SPLIT
# ─────────────────────────────────────────────────────────────────────────────
print("\n[4] Feature Scaling (StandardScaler — zero mean, unit variance):")
X = df[features_clf]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("  Applied to all 10 MLPClassifier input features.")
for i, col in enumerate(features_clf):
  print(f"    {col:<22}  mean={scaler.mean_[i]:.3f}, std={scaler.scale_[i]:.3f}")

X_reg = df[features_reg]
scaler_reg = StandardScaler()
X_reg_scaled = scaler_reg.fit_transform(X_reg)
y_reg = df[["likes", "shares", "comments"]].values

print("\n[5] Train / Test Split (80 / 20, stratified, random_state=42):")
X_train, X_test, y_train, y_test = train_test_split(
  X_scaled, y, test_size=0.2, random_state=42, stratify=y
)
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
  X_reg_scaled, y_reg, test_size=0.2, random_state=42
)

print(f"  Training : {len(X_train)} samples")
print(f"  Testing  : {len(X_test)} samples")
print(f"  Train class dist → Low: {(y_train == 0).sum()}  High: {(y_train == 1).sum()}")
print(f"  Test  class dist → Low: {(y_test == 0).sum()}   High: {(y_test == 1).sum()}")

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 4 — MODEL ARCHITECTURE & TRAINING
# ─────────────────────────────────────────────────────────────────────────────
print("\n[6] MLP Model Architecture:")
print("  Hidden layers : (100, 50)")
print("  Activation    : ReLU")
print("  Solver        : Adam (adaptive learning rate)")
print("  Max iterations: 300")
print("  Early stopping: enabled (patience=20, val_fraction=0.10)")

mlp_clf = MLPClassifier(
  hidden_layer_sizes=(100, 50),
  activation="relu",
  solver="adam",
  learning_rate="adaptive",
  max_iter=300,
  random_state=42,
  early_stopping=True,
  validation_fraction=0.1,
  n_iter_no_change=20,
  verbose=0,
)

mlp_reg = MLPRegressor(
  hidden_layer_sizes=(100, 50),
  activation="relu",
  solver="adam",
  learning_rate="adaptive",
  max_iter=300,
  random_state=42,
  early_stopping=True,
  validation_fraction=0.1,
  n_iter_no_change=20,
)

print("\n[7] Training MLPClassifier...")
mlp_clf.fit(X_train, y_train)
print(f"  ✓ Done — converged at iteration {mlp_clf.n_iter_}, final loss: {mlp_clf.loss_:.4f}")

print("\n[7b] Training MLPRegressor (multi-output: likes, shares, comments)...")
mlp_reg.fit(X_train_reg, y_train_reg)
print(f"  ✓ Done — converged at iteration {mlp_reg.n_iter_}, final loss: {mlp_reg.loss_:.4f}")

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 5 — CLASSIFICATION EVALUATION
# ─────────────────────────────────────────────────────────────────────────────
y_train_pred = mlp_clf.predict(X_train)
y_test_pred = mlp_clf.predict(X_test)

train_accuracy  = accuracy_score(y_train, y_train_pred)
train_precision = precision_score(y_train, y_train_pred)
train_recall    = recall_score(y_train, y_train_pred)
train_f1        = f1_score(y_train, y_train_pred)

test_accuracy  = accuracy_score(y_test, y_test_pred)
test_precision = precision_score(y_test, y_test_pred)
test_recall    = recall_score(y_test, y_test_pred)
test_f1        = f1_score(y_test, y_test_pred)

cm_train = confusion_matrix(y_train, y_train_pred)
cm_test  = confusion_matrix(y_test,  y_test_pred)

print("\n" + "=" * 70)
print("TRAINING SET — CLASSIFICATION PERFORMANCE")
print("=" * 70)
print(f"  Accuracy : {train_accuracy:.4f}  ({train_accuracy * 100:.2f}%)")
print(f"  Precision: {train_precision:.4f}")
print(f"  Recall   : {train_recall:.4f}")
print(f"  F1-Score : {train_f1:.4f}")
print("\nClassification Report (Training):")
print(classification_report(y_train, y_train_pred, target_names=["Low Engagement", "High Engagement"]))
print("Confusion Matrix (Training):")
print(cm_train)
print(f"  TN={cm_train[0,0]}  FP={cm_train[0,1]}  FN={cm_train[1,0]}  TP={cm_train[1,1]}")

print("\n" + "=" * 70)
print("TESTING SET — CLASSIFICATION PERFORMANCE")
print("=" * 70)
print(f"  Accuracy : {test_accuracy:.4f}  ({test_accuracy * 100:.2f}%)")
print(f"  Precision: {test_precision:.4f}")
print(f"  Recall   : {test_recall:.4f}")
print(f"  F1-Score : {test_f1:.4f}")
print("\nClassification Report (Testing):")
print(classification_report(y_test, y_test_pred, target_names=["Low Engagement", "High Engagement"]))
print("Confusion Matrix (Testing):")
print(cm_test)
print(f"  TN={cm_test[0,0]}  FP={cm_test[0,1]}  FN={cm_test[1,0]}  TP={cm_test[1,1]}")

# ROC-AUC
y_score = mlp_clf.predict_proba(X_test)[:, 1]
fpr, tpr, _ = roc_curve(y_test, y_score)
roc_auc_val = auc(fpr, tpr)
print(f"\n  ROC-AUC (test set): {roc_auc_val:.4f}")

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 6 — REGRESSION EVALUATION
# ─────────────────────────────────────────────────────────────────────────────
y_pred_reg = mlp_reg.predict(X_test_reg)
reg_targets = ("likes", "shares", "comments")
r2_per  = r2_score(y_test_reg, y_pred_reg, multioutput="raw_values")
mae_per = mean_absolute_error(y_test_reg, y_pred_reg, multioutput="raw_values")
mse_per = np.array(
  [mean_squared_error(y_test_reg[:, i], y_pred_reg[:, i]) for i in range(3)],
  dtype=float,
)
reg_r2  = float(np.mean(r2_per))
reg_mae = float(np.mean(mae_per))
reg_mse = float(np.mean(mse_per))

print("\n" + "=" * 70)
print("REGRESSION — TEST SET PERFORMANCE  (predict likes, shares, comments)")
print("=" * 70)
print(f"  {'Target':<12}  {'MAE':>8}  {'MSE':>10}  {'R²':>8}")
print("  " + "-" * 44)
for i, name in enumerate(reg_targets):
  print(f"  {name:<12}  {mae_per[i]:>8.2f}  {mse_per[i]:>10.2f}  {r2_per[i]:>8.4f}")
print("  " + "-" * 44)
print(f"  {'Average':<12}  {reg_mae:>8.2f}  {reg_mse:>10.2f}  {reg_r2:>8.4f}")

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 7 — OVERFITTING ANALYSIS
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 70)
print("OVERFITTING ANALYSIS — TRAIN vs TEST GAP")
print("=" * 70)
print(f"  {'Metric':<12}  {'Training':>10}  {'Testing':>10}  {'Difference':>12}  {'Status':>12}")
print("  " + "-" * 60)
metrics_oof = [
  ("Accuracy",  train_accuracy,  test_accuracy),
  ("Precision", train_precision, test_precision),
  ("Recall",    train_recall,    test_recall),
  ("F1-Score",  train_f1,        test_f1),
]
for name, tr, te in metrics_oof:
  diff = abs(tr - te)
  flag = "✓ Minimal" if diff < 0.02 else ("⚠ Moderate" if diff < 0.05 else "✗ Overfit")
  print(f"  {name:<12}  {tr:>10.4f}  {te:>10.4f}  {diff:>12.4f}  {flag:>12}")

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 8 — CROSS-VALIDATION (5-Fold Stratified)
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 70)
print("CROSS-VALIDATION — 5-FOLD STRATIFIED (CLO 3: Model Refinement)")
print("=" * 70)
print("  Running 5-fold stratified cross-validation on the full dataset...")

cv_model = MLPClassifier(
  hidden_layer_sizes=(100, 50),
  activation="relu",
  solver="adam",
  learning_rate="adaptive",
  max_iter=300,
  random_state=42,
  early_stopping=True,
  validation_fraction=0.1,
  n_iter_no_change=20,
)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_results = cross_validate(
  cv_model,
  X_scaled,
  y,
  cv=skf,
  scoring=["accuracy", "precision", "recall", "f1"],
  return_train_score=True,
)

cv_metrics = {
  "Accuracy":  ("test_accuracy",  "train_accuracy"),
  "Precision": ("test_precision", "train_precision"),
  "Recall":    ("test_recall",    "train_recall"),
  "F1-Score":  ("test_f1",        "train_f1"),
}

print(f"\n  {'Metric':<12}  {'CV Mean':>9}  {'CV Std':>8}  {'CV Min':>8}  {'CV Max':>8}")
print("  " + "-" * 50)
cv_summary = {}
for label, (test_key, _) in cv_metrics.items():
  scores = cv_results[test_key]
  cv_summary[label] = scores
  print(
    f"  {label:<12}  {scores.mean():>9.4f}  {scores.std():>8.4f}  "
    f"{scores.min():>8.4f}  {scores.max():>8.4f}"
  )

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 9 — HYPERPARAMETER SENSITIVITY (CLO 4: Optimization)
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 70)
print("HYPERPARAMETER SENSITIVITY — HIDDEN LAYER CONFIGURATIONS (CLO 4)")
print("=" * 70)
print("  Testing alternative architectures to validate current (100, 50) choice...")

architectures = {
  "(50, 25)":   (50, 25),
  "(75, 40)":   (75, 40),
  "(100, 50)":  (100, 50),   # baseline
  "(128, 64)":  (128, 64),
  "(150, 75)":  (150, 75),
}

arch_results = {}
print(f"\n  {'Architecture':<14}  {'Accuracy':>10}  {'F1-Score':>10}  {'Iterations':>12}")
print("  " + "-" * 52)
for name, sizes in architectures.items():
  m = MLPClassifier(
    hidden_layer_sizes=sizes,
    activation="relu",
    solver="adam",
    learning_rate="adaptive",
    max_iter=300,
    random_state=42,
    early_stopping=True,
    validation_fraction=0.1,
    n_iter_no_change=20,
  )
  m.fit(X_train, y_train)
  preds = m.predict(X_test)
  acc = accuracy_score(y_test, preds)
  f1  = f1_score(y_test, preds)
  arch_results[name] = {"accuracy": acc, "f1": f1, "n_iter": m.n_iter_}
  marker = " ← baseline" if name == "(100, 50)" else ""
  print(f"  {name:<14}  {acc:>10.4f}  {f1:>10.4f}  {m.n_iter_:>12}{marker}")

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 10 — FEATURE IMPORTANCE
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 70)
print("FEATURE IMPORTANCE — LAYER 1 WEIGHTS (absolute mean)")
print("=" * 70)
feature_importance = np.abs(mlp_clf.coefs_[0]).mean(axis=1)
feature_names_short = [
  "Platform", "Post Type", "Likes", "Shares", "Comments",
  "Views", "Year", "Month", "Day of Week", "Week of Year",
]
sorted_idx = np.argsort(feature_importance)[::-1]
for rank, idx in enumerate(sorted_idx, 1):
  print(f"  {rank:>2}. {feature_names_short[idx]:<16}  {feature_importance[idx]:.4f}")

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 11 — CLASSIFICATION vs REGRESSION COMPARISON TABLE
# ─────────────────────────────────────────────────────────────────────────────
comparison_df = pd.DataFrame({
  "Aspect": [
    "Problem type",
    "What we predict",
    "Target (label)",
    "Key inputs (examples)",
    "Output",
  ],
  "Classification": [
    "Categorical prediction",
    "High vs. Low engagement",
    f"1 if likes > median ({engagement_threshold:.0f}), else 0",
    "platform, post type, likes, shares, comments, views, dates",
    "Binary: 1 (High) / 0 (Low)",
  ],
  "Regression": [
    "Continuous prediction (multi-output)",
    "Exact likes, shares, comments counts",
    "Three continuous targets: likes, shares, comments",
    "platform, post type, views, year, month, day, week",
    "Three float values per post",
  ],
})

print("\n" + "=" * 70)
print("CLASSIFICATION vs REGRESSION — TASK COMPARISON")
print("=" * 70)
print(comparison_df.to_string(index=False))

print("\n" + "=" * 70)
print("PERFORMANCE SUMMARY TABLE")
print("=" * 70)
print(f"  {'Metric':<12}  {'Training':>10}  {'Testing':>10}  {'Difference':>12}")
print("  " + "-" * 50)
for name, tr, te in metrics_oof:
  print(f"  {name:<12}  {tr:>10.4f}  {te:>10.4f}  {abs(tr - te):>12.4f}")
print(f"\n  ROC-AUC (test): {roc_auc_val:.4f}")

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 12 — VISUALIZATIONS (13 images + loss curves)
# ─────────────────────────────────────────────────────────────────────────────
print("\n[9] Generating Visualizations...")

# ── helper: style table cells ────────────────────────────────────────────────
def _style_table(tbl, header_color="#2c5282"):
  tbl.auto_set_font_size(False)
  tbl.set_fontsize(10)
  tbl.scale(1.05, 2.15)
  for (row, col), cell in tbl.get_celld().items():
    if row == 0:
      cell.set_facecolor(header_color)
      cell.set_text_props(color="white", fontweight="bold")
      cell.set_height(0.08)
    else:
      cell.set_facecolor("#edf2f7" if row % 2 == 1 else "#ffffff")

# ── 01 Confusion Matrix — Training ───────────────────────────────────────────
fig1, ax1 = plt.subplots(figsize=(8, 6))
sns.heatmap(
  cm_train, annot=True, fmt="d", cmap="Blues", ax=ax1,
  xticklabels=["Low Engagement", "High Engagement"],
  yticklabels=["Low Engagement", "High Engagement"],
  cbar_kws={"label": "Count"},
)
ax1.set_title("Confusion Matrix — Training Set", fontweight="bold", fontsize=14)
ax1.set_ylabel("True Label", fontsize=12)
ax1.set_xlabel("Predicted Label", fontsize=12)
plt.tight_layout()
plt.savefig("01_confusion_matrix_training.png", dpi=300, bbox_inches="tight")
plt.close()
print("✓ Image 01 saved: 01_confusion_matrix_training.png")

# ── 02 Confusion Matrix — Testing ────────────────────────────────────────────
fig2, ax2 = plt.subplots(figsize=(8, 6))
sns.heatmap(
  cm_test, annot=True, fmt="d", cmap="Greens", ax=ax2,
  xticklabels=["Low Engagement", "High Engagement"],
  yticklabels=["Low Engagement", "High Engagement"],
  cbar_kws={"label": "Count"},
)
ax2.set_title("Confusion Matrix — Testing Set", fontweight="bold", fontsize=14)
ax2.set_ylabel("True Label", fontsize=12)
ax2.set_xlabel("Predicted Label", fontsize=12)
plt.tight_layout()
plt.savefig("02_confusion_matrix_testing.png", dpi=300, bbox_inches="tight")
plt.close()
print("✓ Image 02 saved: 02_confusion_matrix_testing.png")

# ── 03 Performance Metrics Comparison ────────────────────────────────────────
fig3, ax3 = plt.subplots(figsize=(10, 6))
metrics_labels = ["Accuracy", "Precision", "Recall", "F1-Score"]
train_scores = [train_accuracy, train_precision, train_recall, train_f1]
test_scores  = [test_accuracy,  test_precision,  test_recall,  test_f1]
x = np.arange(len(metrics_labels))
width = 0.35
bars1 = ax3.bar(x - width / 2, train_scores, width, label="Training", alpha=0.8, color="steelblue")
bars2 = ax3.bar(x + width / 2, test_scores,  width, label="Testing",  alpha=0.8, color="darkorange")
ax3.set_ylabel("Score", fontsize=12)
ax3.set_title("Model Performance Metrics Comparison", fontweight="bold", fontsize=14)
ax3.set_xticks(x)
ax3.set_xticklabels(metrics_labels)
ax3.legend(fontsize=11)
ax3.set_ylim([0, 1.1])
ax3.grid(axis="y", alpha=0.3)
for bars in [bars1, bars2]:
  for bar in bars:
    h = bar.get_height()
    ax3.text(bar.get_x() + bar.get_width() / 2.0, h, f"{h:.3f}", ha="center", va="bottom", fontsize=9)
plt.tight_layout()
plt.savefig("03_performance_metrics_comparison.png", dpi=300, bbox_inches="tight")
plt.close()
print("✓ Image 03 saved: 03_performance_metrics_comparison.png")

# ── 04 Feature Importance ────────────────────────────────────────────────────
fig4, ax4 = plt.subplots(figsize=(10, 7))
sorted_idx_asc = np.argsort(feature_importance)
colors = plt.cm.viridis(np.linspace(0, 1, len(sorted_idx_asc)))
ax4.barh(
  [feature_names_short[i] for i in sorted_idx_asc],
  feature_importance[sorted_idx_asc],
  alpha=0.8,
  color=colors,
)
ax4.set_xlabel("Average Absolute Weight", fontsize=12)
ax4.set_title("Feature Importance (Layer 1 Weights)", fontweight="bold", fontsize=14)
ax4.grid(axis="x", alpha=0.3)
plt.tight_layout()
plt.savefig("04_feature_importance.png", dpi=300, bbox_inches="tight")
plt.close()
print("✓ Image 04 saved: 04_feature_importance.png")

# ── 05 Accuracy Comparison Bar ───────────────────────────────────────────────
fig5, ax5 = plt.subplots(figsize=(8, 6))
colors_acc = ["#2ecc71", "#e74c3c"]
bars5 = ax5.bar(["Training", "Testing"], [train_accuracy, test_accuracy], color=colors_acc, alpha=0.8, width=0.5)
ax5.set_ylabel("Accuracy", fontsize=12)
ax5.set_title("Overall Model Accuracy Comparison", fontweight="bold", fontsize=14)
ax5.set_ylim([0, 1.1])
ax5.grid(axis="y", alpha=0.3)
for bar, acc in zip(bars5, [train_accuracy, test_accuracy]):
  ax5.text(bar.get_x() + bar.get_width() / 2.0, acc + 0.02,
           f"{acc:.4f}\n({acc * 100:.2f}%)", ha="center", va="bottom", fontsize=11, fontweight="bold")
plt.tight_layout()
plt.savefig("05_accuracy_comparison.png", dpi=300, bbox_inches="tight")
plt.close()
print("✓ Image 05 saved: 05_accuracy_comparison.png")

# ── 06 Precision Comparison ──────────────────────────────────────────────────
fig6, ax6 = plt.subplots(figsize=(8, 6))
bars6 = ax6.bar(["Training", "Testing"], [train_precision, test_precision], color=colors_acc, alpha=0.8, width=0.5)
ax6.set_ylabel("Precision", fontsize=12)
ax6.set_title("Model Precision Comparison", fontweight="bold", fontsize=14)
ax6.set_ylim([0, 1.1])
ax6.grid(axis="y", alpha=0.3)
for bar, prec in zip(bars6, [train_precision, test_precision]):
  ax6.text(bar.get_x() + bar.get_width() / 2.0, prec + 0.02, f"{prec:.4f}",
           ha="center", va="bottom", fontsize=11, fontweight="bold")
plt.tight_layout()
plt.savefig("06_precision_comparison.png", dpi=300, bbox_inches="tight")
plt.close()
print("✓ Image 06 saved: 06_precision_comparison.png")

# ── 07 Recall Comparison ─────────────────────────────────────────────────────
fig7, ax7 = plt.subplots(figsize=(8, 6))
bars7 = ax7.bar(["Training", "Testing"], [train_recall, test_recall], color=colors_acc, alpha=0.8, width=0.5)
ax7.set_ylabel("Recall", fontsize=12)
ax7.set_title("Model Recall Comparison", fontweight="bold", fontsize=14)
ax7.set_ylim([0, 1.1])
ax7.grid(axis="y", alpha=0.3)
for bar, rec in zip(bars7, [train_recall, test_recall]):
  ax7.text(bar.get_x() + bar.get_width() / 2.0, rec + 0.02, f"{rec:.4f}",
           ha="center", va="bottom", fontsize=11, fontweight="bold")
plt.tight_layout()
plt.savefig("07_recall_comparison.png", dpi=300, bbox_inches="tight")
plt.close()
print("✓ Image 07 saved: 07_recall_comparison.png")

# ── 08 F1-Score Comparison ───────────────────────────────────────────────────
fig8, ax8 = plt.subplots(figsize=(8, 6))
bars8 = ax8.bar(["Training", "Testing"], [train_f1, test_f1], color=colors_acc, alpha=0.8, width=0.5)
ax8.set_ylabel("F1-Score", fontsize=12)
ax8.set_title("Model F1-Score Comparison", fontweight="bold", fontsize=14)
ax8.set_ylim([0, 1.1])
ax8.grid(axis="y", alpha=0.3)
for bar, f1v in zip(bars8, [train_f1, test_f1]):
  ax8.text(bar.get_x() + bar.get_width() / 2.0, f1v + 0.02, f"{f1v:.4f}",
           ha="center", va="bottom", fontsize=11, fontweight="bold")
plt.tight_layout()
plt.savefig("08_f1_score_comparison.png", dpi=300, bbox_inches="tight")
plt.close()
print("✓ Image 08 saved: 08_f1_score_comparison.png")

# ── 09 All Metrics Combined ──────────────────────────────────────────────────
fig9, ax9 = plt.subplots(figsize=(12, 6))
x9 = np.arange(len(metrics_labels))
b9_1 = ax9.bar(x9 - width / 2, train_scores, width, label="Training", alpha=0.85, color="steelblue")
b9_2 = ax9.bar(x9 + width / 2, test_scores,  width, label="Testing",  alpha=0.85, color="coral")
ax9.set_ylabel("Score", fontsize=12)
ax9.set_xlabel("Metrics", fontsize=12)
ax9.set_title("Complete Performance Metrics Comparison", fontweight="bold", fontsize=14)
ax9.set_xticks(x9)
ax9.set_xticklabels(metrics_labels)
ax9.legend(fontsize=11)
ax9.set_ylim([0, 1.15])
ax9.grid(axis="y", alpha=0.3)
for bars in [b9_1, b9_2]:
  for bar in bars:
    h = bar.get_height()
    ax9.text(bar.get_x() + bar.get_width() / 2.0, h + 0.01, f"{h:.3f}",
             ha="center", va="bottom", fontsize=9)
plt.tight_layout()
plt.savefig("09_all_metrics_combined.png", dpi=300, bbox_inches="tight")
plt.close()
print("✓ Image 09 saved: 09_all_metrics_combined.png")

# ── 10 Classification vs Regression Table ────────────────────────────────────
metrics_compare = pd.DataFrame({
  "Test metric": ["Accuracy", "Precision", "Recall", "F1-Score", "ROC-AUC", "R²", "MAE (avg)", "MSE (avg)"],
  "MLP Classification": [
    f"{test_accuracy:.4f}", f"{test_precision:.4f}", f"{test_recall:.4f}",
    f"{test_f1:.4f}", f"{roc_auc_val:.4f}", "—", "—", "—",
  ],
  "MLP Regression": [
    "—", "—", "—", "—", "—",
    f"{reg_r2:.4f} (avg 3 targets)",
    f"{reg_mae:.2f} (avg)",
    f"{reg_mse:.2f} (avg)",
  ],
})

fig_cmp, (ax_a, ax_b) = plt.subplots(2, 1, figsize=(14, 9.5), gridspec_kw={"height_ratios": [1.2, 1]})
fig_cmp.suptitle("MLP Regression vs Classification — Comparison", fontsize=16, fontweight="bold", y=0.98)
ax_a.axis("off")
ax_a.set_title("Task and Setup Comparison", loc="left", fontsize=12, fontweight="bold", pad=12)
t1 = ax_a.table(cellText=comparison_df.values, colLabels=list(comparison_df.columns), loc="center", cellLoc="left")
_style_table(t1)
ax_b.axis("off")
ax_b.set_title(
  "Test-set Performance  (classification: class metrics; regression: avg over likes/shares/comments)",
  loc="left", fontsize=11, fontweight="bold", pad=12,
)
t2 = ax_b.table(cellText=metrics_compare.values, colLabels=list(metrics_compare.columns), loc="center", cellLoc="center")
_style_table(t2)
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.savefig("10_mlp_regression_vs_classification_table.png", dpi=300, bbox_inches="tight", facecolor="white")
plt.close(fig_cmp)
print("✓ Image 10 saved: 10_mlp_regression_vs_classification_table.png")

# ── 11 Training Loss — Classifier & Regressor side-by-side ───────────────────
lc_c = np.asarray(mlp_clf.loss_curve_, dtype=float)
lc_r = np.asarray(mlp_reg.loss_curve_, dtype=float)
fig11, (ax_c, ax_r) = plt.subplots(1, 2, figsize=(14, 5.2), constrained_layout=True)
fig11.suptitle("MLP Training Loss — Classifier vs Regressor", fontsize=14, fontweight="bold")
ax_c.plot(np.arange(len(lc_c)), lc_c, color="steelblue", linewidth=2, label="Training Loss")
ax_c.set_xlabel("Epoch / Iteration", fontsize=11)
ax_c.set_ylabel("Training Loss", color="steelblue", fontsize=11)
ax_c.tick_params(axis="y", labelcolor="steelblue")
val_s = getattr(mlp_clf, "validation_scores_", None)
if val_s is not None and len(val_s) > 0:
  val_s = np.asarray(val_s, dtype=float)
  ax_cv = ax_c.twinx()
  ax_cv.plot(np.arange(len(val_s)), val_s, color="coral", linestyle="--", linewidth=2, label="Validation Score")
  ax_cv.set_ylabel("Validation Score", color="coral", fontsize=11)
  ax_cv.tick_params(axis="y", labelcolor="coral")
  h1, l1 = ax_c.get_legend_handles_labels()
  h2, l2 = ax_cv.get_legend_handles_labels()
  ax_c.legend(h1 + h2, l1 + l2, loc="upper right", fontsize=9)
else:
  ax_c.legend(loc="upper right", fontsize=9)
ax_c.set_title(f"MLPClassifier (n_iter={mlp_clf.n_iter_})", fontweight="bold", fontsize=12)
ax_c.grid(alpha=0.3)
ax_r.plot(np.arange(len(lc_r)), lc_r, color="darkviolet", linewidth=2, label="Training Loss")
ax_r.set_xlabel("Epoch / Iteration", fontsize=11)
ax_r.set_ylabel("Training Loss", fontsize=11)
ax_r.set_title(f"MLPRegressor (n_iter={mlp_reg.n_iter_})", fontweight="bold", fontsize=12)
ax_r.legend(loc="upper right", fontsize=9)
ax_r.grid(alpha=0.3)
plt.savefig("11_mlp_training_loss_classifier_and_regressor.png", dpi=300, bbox_inches="tight", facecolor="white")
plt.close(fig11)
print("✓ Image 11 saved: 11_mlp_training_loss_classifier_and_regressor.png")

# ── 12 ROC Curve ─────────────────────────────────────────────────────────────
fig12, ax12 = plt.subplots(figsize=(7, 6))
ax12.plot(fpr, tpr, color="steelblue", linewidth=2, label=f"ROC (AUC = {roc_auc_val:.4f})")
ax12.plot([0, 1], [0, 1], color="gray", linestyle="--", linewidth=1, label="Chance (0.50)")
ax12.set_xlabel("False Positive Rate", fontsize=12)
ax12.set_ylabel("True Positive Rate", fontsize=12)
ax12.set_title("MLPClassifier — ROC Curve (Test Set)", fontweight="bold", fontsize=13)
ax12.legend(loc="lower right", fontsize=11)
ax12.grid(alpha=0.3)
ax12.set_aspect("equal", adjustable="box")
plt.tight_layout()
plt.savefig("12_classifier_roc_curve_test.png", dpi=300, bbox_inches="tight", facecolor="white")
plt.close(fig12)
print("✓ Image 12 saved: 12_classifier_roc_curve_test.png")

# ── 13 Regression Predicted vs Actual ────────────────────────────────────────
fig13 = plt.figure(figsize=(14, 7.2), constrained_layout=True)
gs = fig13.add_gridspec(2, 3, height_ratios=[2.1, 1])
fig13.suptitle("MLPRegressor — Test Set: Predicted vs Actual + Metrics", fontsize=13, fontweight="bold")
for i, name in enumerate(reg_targets):
  yt = y_test_reg[:, i]
  yp = y_pred_reg[:, i]
  lo, hi = min(yt.min(), yp.min()), max(yt.max(), yp.max())
  ax_pv = fig13.add_subplot(gs[0, i])
  ax_pv.scatter(yt, yp, alpha=0.5, edgecolors="none", s=28, c="darkviolet")
  ax_pv.plot([lo, hi], [lo, hi], "k--", linewidth=1, label="Perfect fit")
  ax_pv.set_xlabel(f"Actual {name}", fontsize=11)
  ax_pv.set_ylabel(f"Predicted {name}", fontsize=11)
  ax_pv.set_title(name.capitalize(), fontsize=12, fontweight="bold")
  ax_pv.legend(loc="lower right", fontsize=9)
  ax_pv.grid(alpha=0.3)
  ax_pv.text(
    0.03, 0.97,
    f"MAE = {mae_per[i]:.2f}\nMSE = {mse_per[i]:.2f}\nR²  = {r2_per[i]:.4f}",
    transform=ax_pv.transAxes, va="top", ha="left", fontsize=10, family="monospace",
    bbox=dict(boxstyle="round,pad=0.35", facecolor="#f5f0e6", edgecolor="#8b7355", alpha=0.95),
  )
ax_tbl13 = fig13.add_subplot(gs[1, :])
ax_tbl13.axis("off")
tbl_rows = [[n.capitalize(), f"{mae_per[i]:.2f}", f"{mse_per[i]:.2f}", f"{r2_per[i]:.4f}"]
            for i, n in enumerate(reg_targets)]
tbl_rows.append(["Average (uniform)", f"{reg_mae:.2f}", f"{reg_mse:.2f}", f"{reg_r2:.4f}"])
tbl13 = ax_tbl13.table(
  cellText=tbl_rows, colLabels=["Target (test)", "MAE", "MSE", "R²"],
  loc="center", cellLoc="center",
)
tbl13.auto_set_font_size(False)
tbl13.set_fontsize(11)
tbl13.scale(1.05, 2.0)
for (row, col), cell in tbl13.get_celld().items():
  if row == 0:
    cell.set_facecolor("#4a6785")
    cell.set_text_props(color="white", fontweight="bold")
  elif row == len(tbl_rows):
    cell.set_facecolor("#e8ecf0")
  else:
    cell.set_facecolor("#ffffff" if row % 2 else "#f7f9fc")
plt.savefig("13_regression_predicted_vs_actual_test.png", dpi=300, bbox_inches="tight", facecolor="white")
plt.close(fig13)
print("✓ Image 13 saved: 13_regression_predicted_vs_actual_test.png")

# ── 14 Cross-Validation Results ──────────────────────────────────────────────
cv_metric_keys = ["test_accuracy", "test_precision", "test_recall", "test_f1"]
cv_metric_labels = ["Accuracy", "Precision", "Recall", "F1-Score"]
fig14, axes14 = plt.subplots(1, 4, figsize=(16, 5))
fig14.suptitle("5-Fold Stratified Cross-Validation Scores", fontsize=14, fontweight="bold")
for ax, key, label in zip(axes14, cv_metric_keys, cv_metric_labels):
  scores = cv_results[key]
  fold_labels = [f"Fold {i+1}" for i in range(len(scores))]
  colors14 = plt.cm.coolwarm(np.linspace(0.2, 0.8, len(scores)))
  bars14 = ax.bar(fold_labels, scores, color=colors14, alpha=0.85)
  ax.axhline(scores.mean(), color="red", linestyle="--", linewidth=1.5, label=f"Mean={scores.mean():.4f}")
  ax.set_title(label, fontweight="bold", fontsize=12)
  ax.set_ylabel("Score", fontsize=10)
  ax.set_ylim([max(0, scores.min() - 0.02), min(1.05, scores.max() + 0.04)])
  ax.legend(fontsize=9)
  ax.grid(axis="y", alpha=0.3)
  for bar, sc in zip(bars14, scores):
    ax.text(bar.get_x() + bar.get_width() / 2.0, sc + 0.003, f"{sc:.3f}",
            ha="center", va="bottom", fontsize=8.5)
  ax.tick_params(axis="x", rotation=25)
plt.tight_layout()
plt.savefig("14_cross_validation_results.png", dpi=300, bbox_inches="tight", facecolor="white")
plt.close(fig14)
print("✓ Image 14 saved: 14_cross_validation_results.png")

# ── 15 Hyperparameter Sensitivity ────────────────────────────────────────────
arch_names = list(arch_results.keys())
arch_acc   = [arch_results[k]["accuracy"] for k in arch_names]
arch_f1    = [arch_results[k]["f1"] for k in arch_names]
x15 = np.arange(len(arch_names))
fig15, ax15 = plt.subplots(figsize=(11, 6))
b15_1 = ax15.bar(x15 - 0.2, arch_acc, 0.35, label="Accuracy", alpha=0.8, color="steelblue")
b15_2 = ax15.bar(x15 + 0.2, arch_f1,  0.35, label="F1-Score", alpha=0.8, color="coral")
ax15.set_xticks(x15)
ax15.set_xticklabels(arch_names, fontsize=11)
ax15.set_ylabel("Score", fontsize=12)
ax15.set_title("Hyperparameter Sensitivity — Hidden Layer Architectures", fontweight="bold", fontsize=14)
ax15.set_ylim([0.95, 1.01])
ax15.legend(fontsize=11)
ax15.grid(axis="y", alpha=0.3)
ax15.axvline(x=2, color="green", linestyle=":", linewidth=1.8, label="Baseline (100,50)")
for bar, val in list(zip(b15_1, arch_acc)) + list(zip(b15_2, arch_f1)):
  ax15.text(bar.get_x() + bar.get_width() / 2.0, val + 0.0008, f"{val:.4f}",
            ha="center", va="bottom", fontsize=8.5)
plt.tight_layout()
plt.savefig("15_hyperparameter_sensitivity.png", dpi=300, bbox_inches="tight", facecolor="white")
plt.close(fig15)
print("✓ Image 15 saved: 15_hyperparameter_sensitivity.png")

# ── 16 Overfitting Gap Chart ──────────────────────────────────────────────────
oof_labels = ["Accuracy", "Precision", "Recall", "F1-Score"]
oof_gaps   = [abs(tr - te) for _, tr, te in metrics_oof]
fig16, ax16 = plt.subplots(figsize=(9, 5))
bar_colors = ["#27ae60" if g < 0.02 else ("#f39c12" if g < 0.05 else "#e74c3c") for g in oof_gaps]
bars16 = ax16.bar(oof_labels, oof_gaps, color=bar_colors, alpha=0.85, width=0.5)
ax16.axhline(0.02, color="orange", linestyle="--", linewidth=1.5, label="2% threshold (minimal)")
ax16.axhline(0.05, color="red",    linestyle="--", linewidth=1.5, label="5% threshold (moderate)")
ax16.set_ylabel("Absolute Train–Test Difference", fontsize=12)
ax16.set_title("Overfitting Analysis — Train vs Test Gap per Metric", fontweight="bold", fontsize=14)
ax16.set_ylim([0, 0.08])
ax16.legend(fontsize=10)
ax16.grid(axis="y", alpha=0.3)
for bar, gap in zip(bars16, oof_gaps):
  ax16.text(bar.get_x() + bar.get_width() / 2.0, gap + 0.001, f"{gap:.4f}",
            ha="center", va="bottom", fontsize=11, fontweight="bold")
plt.tight_layout()
plt.savefig("16_overfitting_analysis.png", dpi=300, bbox_inches="tight", facecolor="white")
plt.close(fig16)
print("✓ Image 16 saved: 16_overfitting_analysis.png")

# ─────────────────────────────────────────────────────────────────────────────
# FINAL SUMMARY
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 70)
print("FINAL MODEL SUMMARY")
print("=" * 70)
print(f"  Architecture        : (100, 50) — ReLU, Adam, adaptive lr")
print(f"  Features (clf)      : {X_train.shape[1]}   |   Features (reg): {X_train_reg.shape[1]}")
print(f"  Training samples    : {X_train.shape[0]}  |   Testing samples: {X_test.shape[0]}")
print(f"  Classifier iter.    : {mlp_clf.n_iter_}   |   Final loss: {mlp_clf.loss_:.4f}")
print(f"  Regressor iter.     : {mlp_reg.n_iter_}   |   Final loss: {mlp_reg.loss_:.4f}")
print()
print(f"  Test Accuracy       : {test_accuracy:.4f}  ({test_accuracy * 100:.2f}%)")
print(f"  Test Precision      : {test_precision:.4f}")
print(f"  Test Recall         : {test_recall:.4f}")
print(f"  Test F1-Score       : {test_f1:.4f}")
print(f"  Test ROC-AUC        : {roc_auc_val:.4f}")
print(f"  Regression R² (avg) : {reg_r2:.4f}")
print(f"  5-Fold CV Accuracy  : {cv_results['test_accuracy'].mean():.4f} ± {cv_results['test_accuracy'].std():.4f}")

best_metric = max(
  [("Accuracy", test_accuracy), ("Precision", test_precision),
   ("Recall", test_recall), ("F1-Score", test_f1)],
  key=lambda x: x[1],
)
print(f"\n  Best metric (test)  : {best_metric[0]} = {best_metric[1]:.4f}")
print()
print("  Visualizations saved:")
print("    01–02: Confusion matrices (train / test)")
print("    03   : Performance metrics comparison")
print("    04   : Feature importance (Layer 1 weights)")
print("    05–08: Individual metric bars (accuracy, precision, recall, F1)")
print("    09   : All metrics combined")
print("    10   : Classification vs Regression comparison table")
print("    11   : Training loss curves (classifier & regressor)")
print("    12   : ROC curve (test set)")
print("    13   : Regression predicted vs actual + metrics table")
print("    14   : 5-fold cross-validation results  [NEW — CLO 3]")
print("    15   : Hyperparameter sensitivity       [NEW — CLO 4]")
print("    16   : Overfitting analysis gap chart   [NEW — CLO 2]")
print()
print("=" * 70)
print("Evaluation & Refinement Complete!")
print("=" * 70)